-- updated_at 자동 갱신용 함수/트리거 (PostgreSQL은 ON UPDATE CURRENT_TIMESTAMP 문법이 없음)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP; -- UPDATE 시 updated_at을 현재 시각으로 갱신
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================
-- member (회원 테이블)
-- =========================
CREATE TABLE member (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 회원 고유 식별자 (자동 증가)
    username    VARCHAR(50)  NOT NULL UNIQUE,                         -- 로그인 아이디 (중복 불가)
    password    VARCHAR(255) NOT NULL,                                -- 암호화된 비밀번호
    email       VARCHAR(100) NOT NULL UNIQUE,                         -- 이메일 (중복 불가)
    role        VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',            -- 권한 (ROLE_USER / ROLE_ADMIN)
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP       -- 가입 일시
);

-- =========================
-- todo (투두 테이블)
-- =========================
CREATE TABLE todo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 투두 고유 식별자 (자동 증가)
    member_id   BIGINT       NOT NULL,                                -- 작성한 회원 ID (member.id 참조)
    title       VARCHAR(200) NOT NULL,                                -- 투두 제목
    content     TEXT,                                                 -- 투두 상세 내용
    is_done     BOOLEAN      NOT NULL DEFAULT FALSE,                  -- 완료 여부 (false=미완료, true=완료)
    due_date    DATE,                                                 -- 마감 기한
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 생성 일시
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 수정 일시 (UPDATE 시 트리거로 자동 갱신)
    CONSTRAINT fk_todo_member
      FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE -- 회원 삭제 시 투두도 삭제
);

-- todo 테이블에서 UPDATE 발생 시 updated_at 자동 갱신 트리거
CREATE TRIGGER trg_todo_updated_at
BEFORE UPDATE ON todo
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- gallery (갤러리 테이블)
-- =========================
CREATE TABLE gallery (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 갤러리 고유 식별자 (자동 증가)
    name        VARCHAR(100) NOT NULL,                                -- 갤러리 이름
    location    VARCHAR(255) NOT NULL,                                -- 갤러리 위치 (층/구역)
    floor_zone  VARCHAR(10)  NOT NULL DEFAULT '1',                  -- 층/구역 코드
    description TEXT,                                                 -- 갤러리 소개
    capacity    INT          NOT NULL,                                -- 최대 수용 인원
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,                   -- 운영 여부 (true=운영중, false=비활성)
    open_time   TIME         NOT NULL DEFAULT TIME '10:00',            -- 관람 시작 시각
    close_time  TIME         NOT NULL DEFAULT TIME '18:00',           -- 관람 종료 시각
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 등록 일시
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP       -- 수정 일시 (UPDATE 시 트리거로 자동 갱신)
);

-- gallery 테이블에서 UPDATE 발생 시 updated_at 자동 갱신 트리거
CREATE TRIGGER trg_gallery_updated_at
BEFORE UPDATE ON gallery
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- reservation (예약 테이블)
-- =========================
CREATE TABLE reservation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 예약 고유 식별자 (자동 증가)
    member_id        BIGINT      NOT NULL,                                 -- 예약한 회원 ID (member.id 참조)
    gallery_id       BIGINT      NOT NULL,                                 -- 예약한 갤러리 ID (gallery.id 참조)
    reservation_date DATE        NOT NULL,                                 -- 관람 날짜
    start_time       TIME        NOT NULL,                                 -- 관람 시작 시간
    end_time         TIME        NOT NULL,                                 -- 관람 종료 시간
    guests           INT,                                                  -- 인원수 (선택)
    contact_info     VARCHAR(20),                                          -- 연락처 (선택)
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',               -- 예약 상태 (PENDING=대기 / APPROVED=확정 / REJECTED=거절)
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,       -- 예약 신청 일시
    updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,       -- 상태 변경/수정 일시 (UPDATE 시 트리거로 자동 갱신)
    CONSTRAINT fk_reservation_member
      FOREIGN KEY (member_id)  REFERENCES member(id)  ON DELETE CASCADE,   -- 회원 삭제 시 예약도 삭제
    CONSTRAINT fk_reservation_gallery
      FOREIGN KEY (gallery_id) REFERENCES gallery(id) ON DELETE CASCADE    -- 갤러리 삭제 시 예약도 삭제
);

-- 갤러리별 + 날짜별 예약 조회 성능 향상용 인덱스
CREATE INDEX idx_gallery_date ON reservation (gallery_id, reservation_date);

-- reservation 테이블에서 UPDATE 발생 시 updated_at 자동 갱신 트리거
CREATE TRIGGER trg_reservation_updated_at
BEFORE UPDATE ON reservation
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE sns_user (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 사용자 고유 식별자 (자동 증가)
    name         VARCHAR(255) NOT NULL,                               -- 닉네임(별명)
    email        VARCHAR(255) NOT NULL,                               -- 이메일(계정)
    provider     VARCHAR(50)  NOT NULL,                               -- OAuth 제공자 (google/kakao/naver)
    provider_id  VARCHAR(100) NOT NULL,                               -- 제공자 측 사용자 고유 ID
    picture      VARCHAR(255) NOT NULL,                               -- 프로필 이미지 경로(URL/파일 경로)
    user_role    VARCHAR(255) DEFAULT 'ROLE_USER',                    -- 사용자 권한 (기본값 ROLE_USER)
    created_date DATE DEFAULT CURRENT_DATE,                           -- 생성일 (기본값: 현재 날짜)
    CONSTRAINT uq_sns_user_provider UNIQUE (provider, provider_id)    -- provider + provider_id 조합 유니크
);